# Generated by Django 4.2.7 on 2023-12-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('unit', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='unit',
        ),
    ]
